# npm run deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
name: Deploy storybook
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: yarn bootstrap
      - run: cd packages/stories && npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}